###
POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 4557,
  "protocol": "http",
  "name": "Exercício 11 - Criar Tarefa",
  "stubs": [
    {
      //Exercício 10
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/tasks",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "contains": {
            "body": "\"title\":\"duplicate\""
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 409,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "duplicate_task",
              "message": "A tarefa com este título já existe."
            }
          }
        }
      ]
    },
    {
      //Exercício 11
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/tasks"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": {
              "Content-Type": "application/json",
              "Location": "/api/tasks/123" 
            },
            "body": {
              "id": 123,
              "status": "created",
              "message": "Tarefa criada com sucesso."
            }
          }
        }
      ]
    }
  ]
}


### 2. Teste

POST http://localhost:4557/api/tasks
Content-Type: application/json

{
    "title": "Completar Mountebank",
}


### 3. Teste de Conflito

POST http://localhost:4557/api/tasks
Content-Type: application/json

{
    "title": "duplicate",
}